-- USERS table
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT UNIQUE NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    PASSWORD TEXT NOT NULL
);

-- PRODUCTS table
DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE PRODUCTS (
    P_ID TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    PRICE REAL NOT NULL,
    COLOUR TEXT,
    BRAND TEXT,
    IMG TEXT,
    RATINGCOUNT INTEGER DEFAULT 0,
    AVG_RATING REAL DEFAULT 0,
    DESCRIPTION TEXT,
    P_ATTRIBUTES TEXT,
    TOP_TYPE TEXT,
    SLEEVE_LENGTH TEXT,
    OCCASION TEXT,
    PRINT_PATTERN TEXT,
    FABRIC TEXT,
    HAS_DUPATTA INTEGER,
    IS_SUSTAINABLE INTEGER,
    SEARCH_TEXT TEXT
);

-- ORDERS table with foreign keys to USERS and PRODUCTS
DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS (
    ORDER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRODUCT_ID TEXT NOT NULL,
    USER_ID INTEGER NOT NULL,
    PRODUCT_DESCRIPTION TEXT,
    ORDER_DATE DATE,
    SHIPPING_DATE DATE,
    DELIVERY_DATE DATE,
    AMOUNT REAL NOT NULL,
    STATUS TEXT CHECK(STATUS IN ('ordered','packed','shipped','out for delivery','delivered')),
    DELIVERY_PARTNER_NO TEXT,
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(P_ID)
);


